@startuml ClasificadorAnime
left to right direction
skinparam roundcorner 20
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam defaultFontName "Arial"

legend top
|= Símbolo |= Relación |= Descripción |
| <|-- | Herencia | Relación "es-un" |
| *--  | Composición | Parte-de (ciclo de vida dependiente) |
| o--  | Agregación  | Tiene-un (ciclo de vida independiente) |
| -->  | Asociación  | Vinculación estructural |
| ..>  | Dependencia | Uso puntual (no estructural) |
endlegend

'----------- PAQUETES -------------'

package ui {
  class AnimeUI {
    +mostrarMenu(): void
    +mostrarAnimes(animes: List<Anime>): void
    +crearAnime(): void
    +filtrarPorGenero(): void
    +filtrarPorEstado(): void
    +filtrarPorCalificacion(): void
    +crearLista(): void
    +agregarAnimeALista(): void
    +mostrarListas(): void
  }
}

package service {
  interface IAnimeService {
    +crearAnime(titulo: String, anioLanzamiento: int, estudio: Estudios,
    cantidadCapitulos: int, estado: EstadosAnime,
    calificacion: int, generos: List<Generos>): void
    +obtenerTodos(): List<Anime>
    +ordenarAnimes(criterio: CriterioOrdenamiento, orden: Ordenamientos): List<Anime>
    +filtrar(filtro: CriterioFiltrado): List<Anime>
    +actualizarAnime(anime: Anime): void
    +eliminarAnime(titulo: String): void
    +obtenerPromedioCalificacionesGlobal(): Double
    +top3GenerosMasFrecuentes(): List<Generos>
    +cantidadAnimesPorEstado(): Map<EstadosAnime, Integer>
    +obtenerPromedioCalificacionPorGenero(): Map<Generos, Double>
    +recomendar(criterio: CriterioRecomendacion, n: int): List<Anime>
  }

  interface IListaService {
    +crearLista(nombre: String): void
    +agregarAnimeALista(idLista: int, idAnime: int): void
    +eliminarAnimeDeLista(idLista: int, idAnime: int): void
    +eliminarLista(nombre: String): void
    +obtenerListasQueContienenAnime(idAnime: int): List<Lista>
    +listarListas(): List<Lista>
  }

  interface CriterioOrdenamiento {
    +ordenar(animes: List<Anime>): List<Anime>
    +ordenar(animes: List<Anime>, orden: Ordenamientos): List<Anime>
  }

  interface CriterioFiltrado {
    +filtrar(animes: List<Anime>): List<Anime>
  }

  interface CriterioRecomendacion {
    +recomendar(animes: List<Anime>, n: int): List<Anime>
  }

  class AnimeServiceImpl {
    -animeRepository: IAnimeRepository
  }

  class ListaServiceImpl {
    -listaRepository: IListaRepository
  }

  abstract class OrdenadorTemplate {
    #obtenerValor(anime: Anime): int
    +ordenar(animes: List<Anime>): List<Anime>
    +ordenar(animes: List<Anime>, orden: Ordenamientos): List<Anime>
  }

  abstract class OrdenadorTemplateString {
    #obtenerValorString(anime: Anime): String
    +ordenar(animes: List<Anime>): List<Anime>
    +ordenar(animes: List<Anime>, orden: Ordenamientos): List<Anime>
  }

  class OrdenarPorCalificaciones
  class OrdenarPorAnio
  class OrdenarPorTitulo
  class OrdenarPorGenero

  abstract class FiltradorTemplate {
    +filtrar(animes: List<Anime>): List<Anime>
    #cumpleCondicion(anime: Anime): boolean
  }

  class FiltroPorGenero {
    -generoBuscado: Generos
  }

  class FiltroPorEstado {
    -estadoBuscado: EstadosAnime
  }

  class FiltroPorCalificacionMinima {
    -calificacionMinima: int
  }


  class RecomendacionTopN
  class RecomendacionPorGenero {
    -genero: Generos
  }

}

package repository {

  interface IAnimeRepository {
    +guardarAnime(anime: Anime): void
    +obtenerAnimesPorTitulo(titulo: String): List<Anime>
    +obtenerAnimesPorRangoAnios(anioDesde: int, anioHasta: int): List<Anime>
    +obtenerAnimesPorGenero(genero: Generos): List<Anime>
    +obtenerAnimePorId(id: int): Anime
    +eliminarAnime(titulo: String): void
    +actualizarAnime(anime: Anime): void
    +listarAnimes(): List<Anime>
  }

  class AnimeRepositoryArchivo {
    -ARCHIVO_ANIMES: String
    -guardarEnArchivo(animes: List<Anime>): void
    -cargarDesdeArchivo(): List<Anime>
  }

  interface IListaRepository {
    +guardarLista(lista: Lista): Lista
    +obtenerListaPorNombre(nombre: String): Lista
    +obtenerListaPorId(idLista: int): Lista
    +obtenerListasPorIdAnime(idAnime: int): List<Lista>
    +listarListas(): List<Lista>
    +actualizarLista(lista: Lista): void
  }

  class ListaRepositoryArchivo {
    -ARCHIVO_LISTAS: String
    -guardarEnArchivo(listas: List<Lista>): void
    -cargarDesdeArchivo(): List<Lista>
  }

  class PersistenciaException
  class NoEncontradoException
}


package model {
  class Anime {
    -id: int
    -titulo: String
    -anioLanzamiento: int
    -estudio: Estudios
    -cantidadCapitulos: int
    -estado: EstadoAnime
    -calificacionUsuarios: int
    -generos: List<Generos>
    +Anime(titulo: String, anioLanzamiento: int, cantidadCapitulos: int, estado: EstadoAnime, calificacion: int, generos: List<Generos>): void
    +validarTitulo(titulo: String): void
    +validarAnio(anioLanzamiento: int): void
    +validarCapitulos(cantidadCapitulos: int): void
    +validarCalificacion(calificacionUsuarios: int): void
    +validarGeneros(generos: List<Generos>): void
    +setEstado(estado: EstadoAnime): void
    +agregarGenero(genero: Generos): void
    +eliminarGenero(genero: Generos): void
    #setId(id: int): void
    ' solo debe ser llamado por el repository quien es el que asigna el id
  }

  class Lista {
    -id: int
    -nombre: String
    -animesId: List<int>
    +Lista(id: int, nombre: String): void
    +existeAnime(idAnime: int): boolean
    +agregarAnime(idAnime: int): void
  }


  enum Estudios {
    Ufotable
    MAPPA
    Kyoto Animation
    Bones
    Wit Studio
  }

  enum EstadoAnime {
    POR_VER
    VIENDO
    FINALIZADO
    ABANDONADO
  }

  enum Generos {
    SHONEN
    SHOJO
    SEINEN
    JOSEI
    MECHA
    ISEKAI
    SLICE_OF_LIFE
  }

  enum Ordenamientos {
    ASC
    DESC
  }

  class ValidacionException
  class YaExisteException
}

'----------- RELACIONES -------------'
YaExisteException --|> ValidacionException
CriterioRecomendacion <|.. RecomendacionTopN
CriterioRecomendacion <|.. RecomendacionPorGenero

CriterioFiltrado <|.. FiltradorTemplate
CriterioFiltrado <|.. FiltroPorGenero

FiltradorTemplate <|-- FiltroPorEstado
FiltradorTemplate <|-- FiltroPorCalificacionMinima
CriterioOrdenamiento <|.. OrdenadorTemplate
CriterioOrdenamiento <|.. OrdenadorTemplateString

OrdenadorTemplate <|-- OrdenarPorCalificaciones
OrdenadorTemplate <|-- OrdenarPorAnio

OrdenadorTemplateString <|-- OrdenarPorTitulo
OrdenadorTemplateString <|-- OrdenarPorGenero

IAnimeService <|.. AnimeServiceImpl
IListaService <|.. ListaServiceImpl

AnimeServiceImpl ..> IAnimeRepository
ListaServiceImpl ..> IListaRepository
IAnimeRepository <|.. AnimeRepositoryArchivo
IListaRepository <|.. ListaRepositoryArchivo

'---------- NOTAS -----------------'

@enduml
